-- supabase/migrations/20260626_create_couple_questions.sql
CREATE TABLE IF NOT EXISTS couple_questions (
    question_id      TEXT PRIMARY KEY,
    dimension_id     TEXT NOT NULL,
    cluster          TEXT NOT NULL,
    item_type        TEXT NOT NULL,
    reverse          BOOLEAN NOT NULL DEFAULT FALSE,
    stem             TEXT NOT NULL,
    anchor_low       TEXT,
    anchor_high      TEXT,
    apply_prediction BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order       INTEGER NOT NULL,
    version          TEXT DEFAULT 'v1'
);

INSERT INTO couple_questions VALUES
('A1-1','money','A','slider',FALSE,'对待钱，我更倾向于','存下来更安心','花在当下更值得',TRUE,1,'v1'),
('A1-2','money','A','slider',FALSE,'面对一笔意外之财，我的第一反应是','先存起来或还贷','先犒劳一下自己/我们',TRUE,2,'v1'),
('A1-3','money','A','likert7',TRUE,'我觉得为了将来，现在省一点是值得的。',NULL,NULL,TRUE,3,'v1'),
('A2-1','intimacy_freq','A','slider',FALSE,'我理想中表达亲密（身体和情感上的靠近）的频率','比大多数情侣更少','比大多数情侣更多',TRUE,4,'v1'),
('A2-2','intimacy_freq','A','slider',FALSE,'当我状态不好时，我更希望','先给我点空间','多抱抱我、多陪陪我',TRUE,5,'v1'),
('A2-3','intimacy_freq','A','likert7',FALSE,'身体上的亲密对我来说是关系里很重要的一部分。',NULL,NULL,TRUE,6,'v1'),
('A3-1','chores','A','slider',FALSE,'家里的活儿该怎么分','最好说清楚、尽量对半','谁有空谁顺手做就行',TRUE,7,'v1'),
('A3-2','chores','A','likert7',FALSE,'我会因为“家务谁做得多”这种事感到不平衡。',NULL,NULL,TRUE,8,'v1'),
('A4-1','children','A','slider',FALSE,'关于要不要孩子','我挺想要 / 想早点要','我倾向不要 / 不着急',TRUE,9,'v1'),
('A4-2','children','A','slider',FALSE,'如果有了孩子，我理想中的带法更偏','多立规矩、严格一些','多给自由、宽松一些',TRUE,10,'v1'),
('A4-3','children','A','likert7',FALSE,'在人生规划里，“有没有孩子”对我是件大事。',NULL,NULL,TRUE,11,'v1'),
('A5-1','inlaws','A','slider',FALSE,'重大决定（比如买房、换工作）要不要先问问父母','应该尊重、听听他们意见','我们俩商量定了就行',FALSE,12,'v1'),
('A5-2','inlaws','A','slider',FALSE,'逢年过节、日常往来，我希望和双方父母','走得近一些、常联系','保持点距离、有自己的小家',FALSE,13,'v1'),
('A5-3','inlaws','A','likert7',FALSE,'另一半和我父母的关系，会明显影响我的心情。',NULL,NULL,FALSE,14,'v1'),
('A6-1','time_space','A','slider',FALSE,'在亲密关系里，我需要的独处空间','很少，越黏越好','挺多，我需要自己的时间',FALSE,15,'v1'),
('A6-2','time_space','A','likert7',FALSE,'就算很相爱，我也需要一些完全属于自己的时间。',NULL,NULL,FALSE,16,'v1'),
('A7-1','career_life','A','slider',FALSE,'在现阶段，我更愿意把精力放在','拼事业、抓机会','顾家庭、过好日子',FALSE,17,'v1'),
('A7-2','career_life','A','slider',FALSE,'如果工作和两人时间冲突，我通常','先把工作扛过去','优先留给我们俩',FALSE,18,'v1'),
('A7-3','career_life','A','likert7',FALSE,'为了事业，我可以接受一段时间牺牲相处时间。',NULL,NULL,FALSE,19,'v1'),
('B1-1','confront','B','likert7',FALSE,'有分歧时，我更可能当场说出来，而不是先憋着。',NULL,NULL,FALSE,20,'v1'),
('B1-2','confront','B','likert7',TRUE,'我不太喜欢把问题摊开谈，更希望它自己过去。',NULL,NULL,FALSE,21,'v1'),
('B1-3','confront','B','likert7',FALSE,'就算会有点尴尬，我也愿意把心里的不满讲清楚。',NULL,NULL,FALSE,22,'v1'),
('B2-1','withdraw','B','likert7',FALSE,'当对方想认真谈一件事时，我容易想岔开或先躲一躲。',NULL,NULL,FALSE,23,'v1'),
('B2-2','withdraw','B','likert7',FALSE,'吵起来的时候，我更可能选择沉默或离开现场。',NULL,NULL,FALSE,24,'v1'),
('B3-1','harsh_startup','B','likert7',FALSE,'一有不满，我比较容易一开口语气就冲。',NULL,NULL,FALSE,25,'v1'),
('B3-2','harsh_startup','B','likert7',TRUE,'提意见时，我一般能先心平气和地说。',NULL,NULL,FALSE,26,'v1'),
('B4-1','constructive','B','likert7',FALSE,'关系出问题时，我更愿意主动沟通去解决，而不是冷战。',NULL,NULL,FALSE,27,'v1'),
('B4-2','constructive','B','likert7',TRUE,'遇到矛盾，我有时会用冷暴力或翻旧账。',NULL,NULL,FALSE,28,'v1'),
('B4-3','constructive','B','likert7',FALSE,'就算很失望，我也会试着给关系一点耐心和时间。',NULL,NULL,FALSE,29,'v1'),
('B4-4','constructive','B','likert7',TRUE,'不顺心的时候，我容易动“算了不如分开”的念头。',NULL,NULL,FALSE,30,'v1'),
('C1-1','values_transcend','C','slider',FALSE,'对我更重要的是','公平、帮助他人、与人为善','个人成就、能力、影响力',TRUE,31,'v1'),
('C1-2','values_transcend','C','likert7',FALSE,'看到别人需要帮助，我常会愿意搭把手，哪怕对自己没好处。',NULL,NULL,TRUE,32,'v1'),
('C1-3','values_transcend','C','likert7',TRUE,'“做出一番成绩、被人认可”对我很重要。',NULL,NULL,TRUE,33,'v1'),
('C2-1','values_openness','C','slider',FALSE,'我更看重','稳定、熟悉、按部就班','新鲜、变化、敢于冒险',TRUE,34,'v1'),
('C2-2','values_openness','C','likert7',FALSE,'比起一成不变，我更喜欢尝试没做过的事。',NULL,NULL,TRUE,35,'v1'),
('C3-1','religiosity','C','likert7',FALSE,'信仰或某种精神追求，在我的生活里挺重要。',NULL,NULL,FALSE,36,'v1'),
('C3-2','religiosity','C','likert7',FALSE,'重要的事情上，我会参考自己的信仰或价值信念来做决定。',NULL,NULL,FALSE,37,'v1'),
('C4-1','filial_authority','C','likert7',FALSE,'就算不完全认同，我也觉得应该尽量顺从父母的意思。',NULL,NULL,FALSE,38,'v1'),
('C4-2','filial_authority','C','likert7',FALSE,'在重要选择上，父母的期待是我会认真考虑的因素。',NULL,NULL,FALSE,39,'v1'),
('D1-1','attach_anxiety','D','likert7',FALSE,'我有时会担心，自己在乎这段关系的程度比对方更深。',NULL,NULL,FALSE,40,'v1'),
('D1-2','attach_anxiety','D','likert7',FALSE,'对方回消息慢一点，我容易胡思乱想。',NULL,NULL,FALSE,41,'v1'),
('D1-3','attach_anxiety','D','likert7',FALSE,'我需要对方常常确认“还爱我”，才比较安心。',NULL,NULL,FALSE,42,'v1'),
('D1-4','attach_anxiety','D','likert7',FALSE,'我会害怕对方哪天突然不爱我了。',NULL,NULL,FALSE,43,'v1'),
('D1-5','attach_anxiety','D','likert7',FALSE,'对方稍微冷淡，我就会很不安。',NULL,NULL,FALSE,44,'v1'),
('D1-6','attach_anxiety','D','likert7',FALSE,'我很介意自己对对方来说到底有多重要。',NULL,NULL,FALSE,45,'v1'),
('D2-1','attach_avoid','D','likert7',FALSE,'我不太习惯向对方袒露最深处的感受。',NULL,NULL,FALSE,46,'v1'),
('D2-2','attach_avoid','D','likert7',FALSE,'太黏太近会让我有点不自在，我需要保持点距离。',NULL,NULL,FALSE,47,'v1'),
('D2-3','attach_avoid','D','likert7',FALSE,'遇到难事，我更习惯自己扛，而不是依靠对方。',NULL,NULL,FALSE,48,'v1'),
('D2-4','attach_avoid','D','likert7',FALSE,'让我完全信任、依赖一个人，是件不容易的事。',NULL,NULL,FALSE,49,'v1'),
('D2-5','attach_avoid','D','likert7',FALSE,'对方想更亲近时，我有时会下意识往后退。',NULL,NULL,FALSE,50,'v1'),
('D2-6','attach_avoid','D','likert7',FALSE,'比起两个人融为一体，我更看重各自的独立。',NULL,NULL,FALSE,51,'v1'),
('E1-1','emotional_stability','E','likert7',TRUE,'我的情绪比较容易因为小事起伏。',NULL,NULL,FALSE,52,'v1'),
('E1-2','emotional_stability','E','likert7',TRUE,'我比一般人更容易感到焦虑或烦躁。',NULL,NULL,FALSE,53,'v1'),
('E1-3','emotional_stability','E','likert7',FALSE,'大多数时候，我的心态都挺稳的。',NULL,NULL,FALSE,54,'v1'),
('E1-4','emotional_stability','E','likert7',TRUE,'压力一大，我就容易慌或乱了阵脚。',NULL,NULL,FALSE,55,'v1'),
('E1-5','emotional_stability','E','likert7',FALSE,'就算遇到糟心事，我也能比较快地平复下来。',NULL,NULL,FALSE,56,'v1'),
('E1-6','emotional_stability','E','likert7',FALSE,'我很少长时间陷在低落或烦躁里。',NULL,NULL,FALSE,57,'v1'),
('E1-7','emotional_stability','E','likert7',FALSE,'情绪上来的时候，我能比较好地管住自己。',NULL,NULL,FALSE,58,'v1')
ON CONFLICT (question_id) DO NOTHING;

COMMENT ON TABLE couple_questions IS '双人题库题干表（58 题）。一行=一道题；item_type=slider/likert7；apply_prediction 标记需 predicted 轮的题';
