CREATE TABLE IF NOT EXISTS questions (
  id            SERIAL PRIMARY KEY,
  question_id   TEXT NOT NULL UNIQUE,
  dimension     TEXT NOT NULL,
  sub_dimension TEXT,
  signal_code   TEXT,
  signal_name   TEXT,
  question_type TEXT,
  stem          TEXT NOT NULL,
  option_a      TEXT NOT NULL,
  score_a       TEXT NOT NULL,
  option_b      TEXT NOT NULL,
  score_b       TEXT NOT NULL,
  option_c      TEXT NOT NULL,
  score_c       TEXT NOT NULL,
  option_d      TEXT NOT NULL,
  score_d       TEXT NOT NULL,
  option_e      TEXT,
  score_e       TEXT,
  source        TEXT,
  design_notes  TEXT,
  version       TEXT DEFAULT 'v0',
  status        TEXT DEFAULT '待审',
  sort_order    INTEGER NOT NULL
);

INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q01','依恋',NULL,'S1','不确定性解读','核心题','你给对方发了一条日常消息，往常他半小时左右就会回。但这次已经过了 3 个小时，你打开聊天框发现"对方正在输入..."消失了又没出现新消息。这时候你脑子里第一个冒出来的念头最接近哪个？','他可能在忙，没法马上回，等会儿就会看到','+2','他看到了但暂时没空回，不影响，我去做自己的事','+1','是不是我刚那条消息说得不合适，让他不想接话了 ★','-1','他是不是不那么在乎我了，或者最近在躲我 ★','-2',NULL,NULL,'C 基于 #69、#104；D 基于 #43、#149；A、B 需自行构造','四个选项在"归因方向"上形成光谱：A外部中性归因 / B情境归因 / C自我归因 / D关系威胁归因。这是内部工作模型的典型拆分。','v0','待审',1);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q02','依恋',NULL,'S2','距离容忍度','核心题','周末你们没有提前约见面。对方从早上到下午一直没发消息给你，你也没发。到下午五点左右，你的感受最接近哪个？','没特别感觉，各忙各的，晚上想起来再聊','+2','偶尔会想他在干嘛，但不焦虑，想问的时候就问一句','+1','有点不舒服，但又觉得是不是我太黏人了，在犹豫要不要先发 ★','-1','已经很焦虑了，一直在盯手机，脑子里想了很多可能 ★','-2',NULL,NULL,'C、D 基于 #99、#46、#67；A 参考 #47、#85 改写','刻意不用"几分钟没回"——那种情境对焦虑端过于敏感，分化不出 +2 和 +1。"半天没互相联系"可以拉开四档。','v0','待审',2);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q03','依恋',NULL,'S3','第三者敏感度','核心题','你刷到对方新发的朋友圈，合照里多了一个你不认识的异性朋友，两人看起来挺熟。你的第一反应最接近？','随便看看，他有自己的朋友很正常','+2','会留意一下，但不会多想，回头聊天可能顺口问一嘴','+1','有点不舒服，纠结要不要主动问他这个人是谁','-1','会去翻他关注列表和评论区，想搞清楚这个人和他什么关系 ★','-2',NULL,NULL,'D 直接来自 #77、#78、#81；其他选项需构造','只测"看到时的即时反应"，不测"约定规则"（后者属边界维度）。⚠️ 风险：D 在女性用户中辨识度高，男性中"翻关注列表"共鸣度可能较低，内测留意性别差异。','v0','待审',3);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q04','依恋',NULL,'S4','激活后表达','核心题','你们认识/在一起一段时间了。最近你发现对方明显没以前热情——消息回得慢、也不主动找你。你通常会怎么做？','直接问他是不是最近有什么变化，把自己的感受讲出来','+2','先观察一段时间，如果持续就坦率地聊一次','+1','自己也变冷淡，等他主动来找我 ★','-1','反复看他的朋友圈、动态、游戏在线状态，揣测他在干嘛 ★','-2',NULL,NULL,'C 基于 #66、#93、#104；D 基于 #77-#83 视奸行为族','C 和 D 都是负分但不同亚型：C "被动-撤退"（焦虑+自尊），D "主动-侦查"（焦虑+控制）。D 更深因涉及越界。','v0','待审',4);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q05','依恋',NULL,'S4','激活后表达','验证题','最近这一周，你能感觉到对方整体比之前抽离——没有具体的矛盾，但约见面找借口、微信也不再像从前那样分享日常。你会？','找个合适的时机，直接问他是不是有什么事影响到你们','+2','先自己稳住，给两三天时间看看，不急着下结论','+1','在脑子里反复想哪里出了问题，但嘴上什么也不说 ★','-1','开始找证据——查聊天记录、翻朋友圈，先确认他是不是变心了 ★','-2',NULL,NULL,'C 基于 #69、#129；D 基于 #77-#83','情境刻意选"对方抽离"而非"吵架后"，避免与冲突维度重叠。【交叉验证】题4 选 A/B 但题5 选 C/D → 标记"社会期望偏差，S4 信号不可信"，降低权重。','v0','待审',5);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D1-Q06','依恋',NULL,'S5','安全感来源','核心题','以下几种相处方式，哪一种最让你觉得"这段关系踏实、我被认真对待"？','不用时时黏在一起，但彼此有默契——下班说一声、忙完报个备','+2','每天有固定的连接时刻，比如睡前的一通视频','+1','消息能及时回复，就算简短也好，让我知道他在线 ★','-1','他把我放在最重要的位置，主动分享一切，让我随时知道他在做什么 ★','-2',NULL,NULL,'A 基于 #47；D 基于 #28、#114；B、C 需构造','光谱是"频率与强度"，不是"爱的语言类型"——B 写选项文案时要突出"频率稳定"，弱化"仪式感"，避免与情感维度 T2 混淆。⚠️ 选项 C 打 -1 还是 0 是产品决策点，见原文档 6.3。','v0','待审',6);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q01','边界',NULL,'S1','越界识别与响应','核心题','一次你不在场时，对方翻看了你的手机或聊天记录，事后承认了。在那个当下，你的反应最接近哪个？','直接告诉他这让我很不舒服，以后不能这样，需要看请先告诉我 ★','+2','当时没说出口，事后冷静下来找机会沟通了这件事','+1','心里很不舒服，但想着算了，可能他就是太在乎我了 ★','-1','反复想是不是自己哪里没让他放心，所以他才会这么做 ★','-2',NULL,NULL,'A 基于 #26、#41；C 基于 #28、#13；D 基于 #40、#99','"翻手机"是边界维度最普遍最不需解释的越界场景。光谱：识别+表达 / 识别+延迟表达 / 识别+合理化 / 不识别+自我归因。','v0','待审',7);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q02','边界',NULL,'S2','自我维持','核心题','回想一下，你和对方在一起几个月之后，对比单身时，你自己的整体生活状态（事业/工作、朋友、独处时间、爱好）发生了哪些变化？最贴近你的描述是？','基本没变，我们都有自己的事情和节奏，见面就好好相处 ★','+2','有些调整，但我自己重要的事和朋友圈都还在','+1','为了多陪对方，渐渐放下了一些自己的事，虽然偶尔会觉得有点累 ★','-1','生活几乎围着对方转，朋友少了，自己的事也搁置了 ★','-2',NULL,NULL,'A 基于 #5、#90、#102；C 基于 #88；D 基于 #23、#16','不用"具体场景"问法，让用户回顾"整体状态变化"——S2 本质是累积的、结构性的状态。','v0','待审',8);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q03','边界',NULL,'S3','异性相处的共识','核心题','关于对方与异性朋友的相处（比如单独吃饭、长时间私聊、有共同爱好的活动等），你和对方目前的状态最接近？','我们聊过这件事，对什么算合适、什么算越界达成了共识，他/她也会主动让我认识他的异性朋友 ★','+2','没专门聊过，但默契上彼此知道分寸，基本不会有让我不舒服的时候','+1','我心里有不舒服但说不出口，担心说了会被觉得控制欲强 ★','-1','我表达过我的不舒服，但他/她不当回事，继续按自己的方式来 ★','-2',NULL,NULL,'A 基于 #91、#92；C 基于 #45；D 基于 #49、#85、#52','焦点锁定在"沟通层面"而非"情绪层面"，与依恋 S3 分工。"主动让我认识异性朋友"来自 #91 真实语言。⚠️ 风险：B 选项可能变成高频"安全选项"，内测后可能需重写让 B 比 A 弱一些。','v0','待审',9);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q04','边界',NULL,'S4','付出与经济对等','核心题','在你们的关系里，关于花销、礼物、出去玩这类付出，目前的整体状态是？','自然形成了对等的状态，谁出多了对方也会找机会请回来，不需要刻意计较 ★','+2','大体均衡，偶尔一方多一点，我们都觉得没关系','+1','我付出明显更多，心里有点不舒服，但说不出口或不好意思提 ★','-1','我已经付出很多了，但越付出越停不下来，不付出反而觉得不安 ★','-2',NULL,NULL,'A 基于 #22；C 基于 #15、#33、#61；D 基于 #19、#101、#103','D 与 S2 自我维持有交集，Agent 2 可做交叉推断。⚠️ 性别敏感：男性用户偏"花钱"，女性用户偏"情绪劳动"。如果目标用户偏女性，C/D 可加入"情绪劳动"表述。','v0','待审',10);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q05','边界',NULL,'S1','越界识别与响应','验证题','对方反复说一句让你不舒服的话——比如翻你以前的旧账、用刺耳的方式评价你、或者总在朋友面前拿你开玩笑。你已经被这件事困扰一段时间了，目前你的状态最接近？','已经直接告诉他这种话伤害了我，要求他停止 ★','+2','准备找个合适的时机正式跟他谈一次','+1','心里委屈，但还没想好怎么开口，先忍着看 ★','-1','反复想是不是自己哪里没做好，所以他才会这样说我 ★','-2',NULL,NULL,'A 基于 #41、#52；C 基于 #29、#75；D 基于 #40、#99','与题1 同信号，情境从"一次性事件"换为"持续性贬低"。【交叉验证】题1 选 A/B 但题5 选 C/D → 标记"对单次越界能识别响应，但对持续性伤害失语"（awareness_gap）。','v0','待审',11);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D2-Q06','边界',NULL,'S5','隐私与独立空间','核心题','关于"看伴侣手机"这件事，你最贴近的态度是？','我不会看，我相信他；就算我有需要用他的手机也会先告诉他 ★','+2','一般不看，觉得情侣之间也应该有自己的空间','+1','觉得情侣应该互相透明，有什么不能让对方看的呢 ★','-1','会偷偷看，或者觉得对方应该让我随时能看才算爱我 ★','-2',NULL,NULL,'A 基于 #26、#93；B 基于 #94；D 基于 #25、#48','只测"对查手机的态度"，窄题干能拿清晰信号。⚠️ 文化敏感：C 选项是中国年轻用户主流观念，打 -1 是产品价值观选择（教育用户而非迎合）。如果不想这样可调整为 0。','v0','待审',12);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q01','冲突',NULL,'S1','表达方式','核心题','对方做了一件让你不舒服的小事——比如答应陪你结果一直在打游戏、跟朋友聊天的时候没顾上你。当时你最有可能怎么开口？','我会跟他说"刚才那样我有点不舒服，我希望下次……"——讲清楚自己的感受和具体想要什么 ★','+2','会撒娇式地表达，比如"你能不能陪我一下嘛，我现在就想你陪着我" ★','+1','会带着情绪开口，会说"你怎么总是这样""你眼里就没有我"这类话 ★','-1','当场会说很伤人的话，比如骂他/贬低他/翻很久之前的旧账 ★','-2',NULL,NULL,'A 基于 #78、#80、#81；B 基于 #77；C 基于 #4、#11；D 基于 #8、#10、#22','Gottman 软启动理论。光谱：具体表达感受+诉求 / 撒娇但无攻击 / 笼统抱怨 / 人身攻击+翻旧账。⚠️ 风险：B "撒娇"在男性用户辨识度低，可改为"我会用比较轻松的方式说"。','v0','待审',13);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q02','冲突',NULL,'S2','修复主动性','核心题','你和对方刚刚吵完一架，现在两个人都在屋里但一个字都不说，僵持了一两个小时。这种时候你最常做的是？','会主动找一个具体的方式打破——倒杯水、点个奶茶、过去抱一下，先让气氛缓下来再说 ★','+2','会先开口，但开口的方式比较生硬，可能就是问一句"还吃饭吗"','+1','心里希望他先来找我，我等着，他不来我也不会主动 ★','-1','直接出门/去玩游戏/睡觉，这事就放着不解决了，等明天再说或者干脆不说 ★','-2',NULL,NULL,'A 基于 #83、#84、#85、#88；C 基于 #11、#16；D 基于 #1、#42','+2 选项强调具体动作而非抽象的"主动沟通"——后者太"政治正确"。A "先让气氛缓下来再说"区分了"修复尝试"（缓气氛）和"立即解决问题"（继续吵）。','v0','待审',14);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q03','冲突',NULL,'S3','责任归因','核心题','一次比较大的冲突过去之后（几个小时或者过了一夜），你心里对这次冲突的看法，最接近哪个？','会冷静下来想我俩各自哪里有问题，会跟他一起复盘——我哪些话不该说、他哪些反应也不对 ★','+2','会想想自己是不是太情绪化了，然后下次注意一下','+1','想来想去都觉得是他的错，他不会沟通/他不在乎我/他根本不懂我 ★','-1','反复想是不是自己哪里不够好，所以他才这样对我 ★','-2',NULL,NULL,'A 基于 #89、#91、#93；C 基于 #33、#75；D 基于 #1、#9','D 是 -2 而非 +1——"自我归因"看似反思但本质是自我攻击，与边界 S1 题5 设计一致。【交叉验证】同一用户在边界题5 和冲突题3 都选 D，标记 awareness_gap。⚠️ "复盘"借自商业语言，如内测反馈刻意，可改为"然后跟他一起聊聊"。','v0','待审',15);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q04','冲突',NULL,'S4','情绪淹没管理','核心题','吵架吵到中间，你能感觉到自己情绪要顶不住了——心跳加快、脑子里一片浆糊、随时可能说出狠话或者哭出来。你最常做的是？','会跟他说"我现在情绪上来了，给我二十分钟冷静一下，我们一会儿再谈"——明确告诉对方，然后真的回来 ★/☆','+2','会自己默默走开或不说话，等情绪好了再回来，但不会主动告诉他要暂停','+1','硬撑着继续吵，知道自己快爆了但停不下来，经常说出后来后悔的话 ★','-1','直接关闭——不说话/出门/几天不理对方，一旦顶不住就把这事彻底放下 ★','-2',NULL,NULL,'A 基于 #94 + Gottman time-out 理论构造；B 基于 #20、#43；C 基于 #10、#28；D 基于 #16、#23、#34、#37、#42','⚠️ 素材稀缺，建议 Gong 老师重点精修 A 选项。A 和 B 区别在"是否明确告诉对方"——Gottman 理论"健康暂停 vs 沉默回避"的核心区分。⚠️ 内测重点：A 是+2 端理想行为，需追问"上次这样做是什么时候"区分真做过 vs "应该这样所以选这个"。','v0','待审',16);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q05','冲突',NULL,'S1','表达方式','验证题','这次冲突不是小事，是你们对一件事（比如未来规划、要不要去某个城市、家庭关系怎么处理）有根本性的不一致。在这种重大分歧的争论里，你说出口的话最接近哪种？','会努力描述自己的立场和理由，听他的立场和理由，即使分歧大也不会攻击他这个人 ★','+2','会激动会大声，但事后会道歉，认同自己刚才的方式不太好','+1','会说一些让他觉得受伤的话——比如"你根本不懂我""你跟你爸/你妈一样" ★','-1','会上升到人身攻击，翻很久之前的旧账，把这件事变成"你这个人就是有问题" ★','-2',NULL,NULL,'A 基于 #79、#92；C 基于 #4、#19；D 基于 #10、#22、#75','与题1 同信号，情境从"日常小事"换为"重大分歧"。前者考察软启动，后者考察压力下不滑入四骑士。【交叉验证】两题都+2 → S1 真稳定；题1+2/题5-1或-2 → S1 不稳定，权重以题5 为高（高压力情境更能反映本质）。','v0','待审',17);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D3-Q06','冲突',NULL,'S5','追逃模式中的角色','核心题','回想你过去的恋爱关系（包括现在这段），冲突中你反复出现的固定模式更接近哪个？','我能看出来"我追他逃"或者"他追我逃"是个固定循环，我会主动停下来不重复这个模式 ★/☆','+2','没特别想过这个问题，每次冲突都是就事论事，没什么固定模式','+1','我经常是"追"的那一方——他冷我就一直找他，直到他要么回应要么彻底炸 ★','-2','我经常是"逃"的那一方——他追我就关闭，沉默/出门/不回消息，直到他放弃 ★','-2',NULL,NULL,'A 基于 EFT 理论构造，语言风格借鉴 #62、#21、#3；C 基于 #11、#39；D 基于 #16、#31、#42、#62','⚠️ 特殊设计：C/D 同分但不同亚型（追/逃），让 Agent 2 同时获取"追逃方向"，对 16 类分型走向价值极高。⚠️ B 选项争议：理论上 +1 但多数用户有模式只是没觉察，建议首版打 +1 配合内测，如选 B 用户在题2/题4 得分明显偏低可调为 0。','v0','待审',18);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q01','情感','全光谱主导偏好','T1-T5','主导爱的语言','主导偏好题','想象一个普通的日子，对方做了下面五件事中的哪一件，会让你最强烈地感觉到"他/她真的爱我"？','当面认真地告诉我，"你今天真的很美/你做这件事真的很厉害"——具体地夸我 ★','T1+2','把手机放下，陪我并排坐着聊一两个小时，只聊我们两个人的话题 ★','T2+2','突然带回来一样我无意中说过"想要"的小东西，我都已经忘了说过 ★','T3+2','在我没察觉的时候，默默把我下个月会用到的东西/会做的事情都准备好了 ★','T4+2','我累了/烦了的时候，他不说话，只是过来抱我一下，什么都不说 ★','T5+2','A 基于 #1、#2、#10；B 基于 #15；C 基于 #22、#34；D 基于 #44、#45、#47；E 基于 #48、#49、#51','"明示偏好题"，5 个选项各对应一种爱的语言。⚠️ A "具体地夸我"刻意强调"具体"而非"我爱你"——后者太通用，无法区分言语肯定型。','v0','待审',19);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q02','情感','T1 言语 vs T4 服务','T1/T4','言语肯定 vs 服务行动','对比题','你最近压力很大，工作不顺、心情很糟。下面两种回应，哪一种更能让你觉得"被爱"？','他认真地告诉我："你已经做得很好了，有事我担着，不要怕" ★','T1+2','他什么都没说，默默把家里收拾了、点了我爱吃的外卖，让我什么都不用操心 ★','T4+2','两种我都需要，但他一定要选一个的话，我希望他先抱我一下再做这些','T5+1','其实我更需要他停下手边的事，坐下来认真听我把心里的话讲完','T2+1',NULL,NULL,'A 基于 #7；B 基于 #51、#39；C 基于 #49；D 基于 #15','A/B 核心对比，C/D 作"半逃选项"——给用户表达"两种都不是核心需求"的出口，避免被迫选择不真实答案。','v0','待审',20);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q03','情感','T2 时刻 vs T5 接触','T2/T5','精心时刻 vs 身体接触','对比题','某个安静的周末下午，你和对方都在家里。下面哪种相处方式会让你觉得"这就是最好的状态"？','我们坐在沙发上，放下手机，聊各种各样的事，聊到忘了时间 ★','T2+2','不需要说话，我靠在他身上看书或追剧，感受到他的体温就很满足 ★','T5+2','各做各的事，但他时不时夸一句我专注的样子很可爱','T1+1','他主动做了我爱吃的下午茶，看着我吃就很满足','T4+1',NULL,NULL,'A 基于 #15；B 基于 #56、#53','题干刻意选"安静的周末下午"——低强度日常情境下偏好更易显露。高强度场景（生病/危机）容易让所有人都选"被陪伴"，拉不开区分度。','v0','待审',21);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q04','情感','T3 惊喜 vs T4 服务','T3/T4','用心小惊喜 vs 服务行动','对比题','在最近的一个月里，对方做的下面哪件事，会让你觉得"他/她是真的把我放在心上"？','我有次随口提了一下想吃某个东西，过了几天他突然带回来——我自己都已经忘了说过 ★','T3+2','我没说，他就把我下次出差要用的东西全准备好了/把我房间的灯泡换了 ★','T4+2','他认真告诉我，我最近某件事做得很不错，看到我成长了','T1+1','他在我加班时来公司楼下接我，陪我走回家边走边聊','T2+1',NULL,NULL,'A 基于 #34、#26；B 基于 #45、#47','A/B 看似很像（都是"对方主动做了一件事"），区分点：A 核心是"被记住的细节"（心理投入），B 核心是"被替我承担"（行动投入）。','v0','待审',22);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q05','情感','T1 言语 vs T2 时刻','T1/T2','言语肯定 vs 精心时刻','对比题','你和对方刚刚发生了一点小别扭，对方意识到自己有点忽略你了。下面哪种"补救"方式更让你觉得舒服？','他认真地说："刚才是我不好，你对我真的很重要，我会注意" ★','T1+2','他什么都没解释，直接放下手机说"我们出去走走吧"，然后专心陪我 ★','T2+2','他过来抱我，什么都不说，但抱得很紧','T5+1','他默默给我端来一杯热水/我爱喝的奶茶，用行动表达','T4+1',NULL,NULL,'A 基于 #0、#7；B 基于 #15、#41','情境是"小别扭后的补救"，与冲突 S2 区分：冲突 S2 测"谁主动+用什么动作"（已吵完一架），本题测"哪种类型让我感到被爱"（小别扭未升级）。如担心重叠，可把"小别扭"改为"我心情有点低落"。','v0','待审',23);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D4-Q06','情感','T3 惊喜 vs T5 接触','T3/T5','用心小惊喜 vs 身体接触','验证补盲题','今天是一个普通的日子，既不是节日，也没有任何特别的事情。下面对方做的哪件事，会让你觉得"啊我真的好幸福"？','突然递给我一个小东西，说"这是上次你说想要的那个，我看到了就给你买了" ★','T3+2','路过我的时候过来摸摸我的头/亲一下我的脸，然后继续做自己的事 ★','T5+2','走过来很认真地告诉我"今天你看起来真的很美/今天我又想到你某件事让我觉得真好"','T1+1','默默把我桌上的零食袋扔掉/把我的手机充上电，继续做自己的事','T4+1',NULL,NULL,'A 基于 #29、#34；B 基于 #55、#52；D 基于 #44、#47','T3 和 T5 的"二次确认题"，给两个类型一次额外 +2 机会，确保 Agent 2 累加打分时不被低估。⚠️ T3 总分仅 6 分（其他类型 8-9 分），建议 Agent 2 对 T3 得分乘 1.4 或改用百分比模式。','v0','待审',24);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q01','风格','直接性','S1','直接性 — 日常需求','核心题','一个普通的日子，你想让对方做某件事（比如想吃某个东西、想出去玩某个地方、想要某个小礼物）。你最常用的方式是？','直接说出来——"我想吃 XX""我想去 XX"，对方答应当然好，不答应也无所谓 ★','+2','会找个合适的时机讲出来，不太绕弯，但不会太突兀','+1','会用暗示的方式，比如分享相关的视频/朋友圈，希望对方能 get 到 ★','-1','不会主动说，如果对方猜到就猜到，猜不到就算了，不强求 ★','-2',NULL,NULL,'A 基于 #10、#22；C 基于 #25；D 基于 #36','"日常想要的小事"是 S1 最纯净情境。A 故意加"答应当然好，不答应也无所谓"，把"直接表达"和"高需求/控制感"区分开（后者是依恋焦虑，本题不测）。','v0','待审',25);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q02','风格','直接性','S1','直接性 — 日常情绪','核心题','对方做了某件让你有点不舒服的小事（不是大问题，只是不太顺心）。你通常会怎么处理？','当下就跟他说"刚才那个让我有点不舒服"，不让自己积着 ★','+2','过一会儿等情绪平稳了会说，但一定会说出来，不会闷着','+1','心里有点闷，但觉得没必要为这种小事开口，自己消化掉 ★','-1','不会说出来，可能会变得安静一点，等他自己察觉问我怎么了 ★','-2',NULL,NULL,'A 基于 #24、#19；C 基于含蓄端通用模式；D 基于 #9','保持在"日常情绪小波动"。C/D 区别：C "不期待对方知道"，D "期待对方主动问"——后者是更深的含蓄。⚠️ 与冲突 S1 题1 同情境锚点，区分点在选项：冲突 S1 测"软启动 vs 攻击人品"，本题测"说不说"。Agent 2 双低画像识别。','v0','待审',26);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q03','风格','直接性','S1','直接性 — 关系定位','验证题','想象你和某个人正在暧昧/确定关系的阶段，你想让两人的关系更明确一些。你最有可能怎么开口？','直接告诉他/她"我对你感兴趣，我们要不要在一起" ★','+2','找一个合适的时机和氛围，认真地聊一次"我们现在是什么关系"','+1','通过更明显的行动表现出我的喜欢，等对方先开口 ★','-1','会一直观望/犹豫，可能错过了也不太敢主动开口 ★','-2',NULL,NULL,'A 基于 #20、#18；D 基于 #5、#33','验证题，从"完全日常"切到"略带压力的日常"。如题1/2 选 +2 但题3 选 -2，说明"日常很直接但关键时刻退缩"——回避型依恋叠加直接性的复合画像。','v0','待审',27);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q04','风格','分享欲','S2','分享欲 — 有趣的事','核心题','你在路上看到了一个特别有意思的东西（比如一只很萌的狗、一个搞笑的标语、一个奇怪的招牌）。你的第一反应是？','马上拍照/录视频发给对方，憋不住地分享，期待他回应 ★','+2','会想分享，但不一定立刻发，可能晚上聊天时再说','+1','不会马上想到分享，自己看完笑笑就过去了，可能后来想起来才说一句 ★','-1','基本不会想到要分享给对方，这种小事自己看到就好 ★','-2',NULL,NULL,'A 基于 #37、#39、#41；D 基于 #52、#55','"有趣的事"不是"日常报备"——这是 S2 真正的测量靶心。低分享端用户核心特征是"区分有趣的事和报备"，所以 D 措辞是"小事自己看到就好"。','v0','待审',28);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q05','风格','分享欲','S2','分享欲 — 下班后状态','核心题','一个工作日下班后，如果今天没什么大事发生，只是平常的一天。你和对方的微信聊天通常是？','我会发很多——今天遇到的人、看到的事、想到的小念头，会刷屏式分享 ★','+2','会有日常的来回，聊聊今天怎么样，但不算特别多','+1','聊几句报备一下吃饭/下班/晚安，没什么内容，但有连接 ★','-1','可能就早晚安，中间不怎么发消息，各忙各的 ★','-2',NULL,NULL,'A 基于 #39、#42；C 基于 #57、#58；D 基于 #55、#60','"没什么大事发生，平常的一天"——把测量从"高情绪事件下分享"剥离，聚焦稳定分享倾向。⚠️ 与依恋 S2 边界：依恋 S2 测"对方不联系时焦不焦虑"，本题测"我自己主不主动联系"。两题交叉可识别"焦虑型回避"（假装无所谓但内心煎熬）。','v0','待审',29);
INSERT INTO questions (question_id,dimension,sub_dimension,signal_code,signal_name,question_type,stem,option_a,score_a,option_b,score_b,option_c,score_c,option_d,score_d,option_e,score_e,source,design_notes,version,status,sort_order)
VALUES ('D5-Q06','风格','分享欲','S2','分享欲 — 被追问时','验证题','对方主动问你"今天怎么样啊""今天发生什么有趣的事了吗"。你最常的回答是？','会被这个问题打开话匣子，叽里咕噜讲半天，中间会冒出更多想说的 ★','+2','会认真回答今天发生的事，但不会扯太远','+1','想了想会说一两件有点意思的事，但很多细节就懒得讲了 ★','-1','通常就回"还行""没啥""一般"，自己确实觉得没什么好说的 ★','-2',NULL,NULL,'A 基于 #11、#41；D 基于 #39、#48、#57','验证题，从"主动分享"切到"被动回应"。如题4/5 选 -2 但题6 选 +2 → "自己不主动但被问会说"，Agent 2 报告可专门解读为"被动型分享者"。','v0','待审',30);
